//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupLeaders
    {
        public int Id { get; set; }
        public int GroupId { get; set; }
        public int EmployeeId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Group Group { get; set; }
    }
}
